[tool.poetry]
name = "pygarden"
version = "0.1.0"
description = ""
authors = ["darclo <darclo@zaclys.net>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
pytest-cov = "^5.0.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
